hosts: [192.168.2.116]
port: 8182
serializer: { 
  className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, 
  config: { 
  ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }
  }
  
